### ISSUE TITLE
An idea for the "Plugins" tab

### ISSUE THREAD

**Issue by Madriix** [unrealircd/unrealircd-webpanel#27]
I updated the webpanel to the latest version in the ftp, and I uploaded two new plugins in the ftp, and it's annoying all the time to go to config.php to add lines in the array there . I thought to myself, it would be nice if the Plugins interface could look like this:

![Sans titre-1](https://user-images.githubusercontent.com/9107640/233771492-4c0a40f5-19df-4347-9e40-e9b4c4599ff3.jpg)

Have you considered doing this or is my idea helpful?

Regards

**Comment by ValwareIRC** [comment]
already have plans, thank you.

**Comment by ValwareIRC** [comment]
also please stop putting me as the authors

**Comment by syzop** [comment]
Yes, exactly, a plugin interface is already planned. Including possibly a central repository, like we already have for UnrealIRCd as unrealircd-contrib. In any case an easy to use (web)interface to install and uninstall plugins, and likely also search through possible plugins that exist (the -contrib thing).

But this will be something for later. We're first trying to stabilize the thing and get a first release.

**Comment by Madriix** [comment]
I updated my 2 plugins, I removed the email, I put my nickname and I even put a capital letter at the beginning of each plugin name :
![Sans titre-1](https://user-images.githubusercontent.com/9107640/233806863-d10ba955-a240-4219-ab44-96e18241910c.jpg)
it's more beautiful
