### ISSUE TITLE
Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.10. in

### ISSUE THREAD

**Issue by maxou4201** [unrealircd/unrealircd-webpanel#3]
hello I have a problem with the panel the installation seems to be going as it should but when I go to https://mon-sit/unrealircd-webpanel/ I have this error
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.10. in /var/www/html/unrealircd-webpanel/vendor/composer/platform_check.php on line 24

**Comment by ValwareIRC** [comment]
The webpanel requires PHP 8 or later. As far as I know it requires special instructions to install and can't be installed with simply `apt install php` etc.

Here are some instructions for:
- [Ubuntu 20/22](https://linuxhint.com/install-php-8-ubuntu-22-04/)
- [Debian](https://www.vultr.com/docs/how-to-install-php-8-on-debian-11/)
- [CentOS](https://www.tecmint.com/install-php-8-on-centos/)

For more installation methods, make a websearch for how to install PHP 8 on your operating system.

Thank you for the note, I will make sure to mention these steps in the README
