### ISSUE TITLE
[Feature Request]: Restructure server details page

### ISSUE THREAD

**Issue by syzop** [unrealircd/unrealircd-webpanel#31]
I was thinking 'Servers' details could get a bit of an overhaul (servers/details.php)
It shows all the info you could possibly want but... i was thinking to throw them in tabs, like you have on the channels details page.
Tabs like:
- 'Details' which contains Basic Information + Extra Information
- 'Channel Modes'
- 'User Modes'
- 'Modules' which contains the data  as you currently show in the modules button (scratch the button)

I was thinking i could do it but then figured, i better work on unrealircd than the panel and also not that important, i mean all the info is already there, so it doesn't improve functionality. Better someone else does it.. some day..

**Comment by ValwareIRC** [comment]
Thanks for the feature request, it's been completed as of 1ddf6415399a4f87d9099a57da0aa59081971981
