### ISSUE TITLE
Third party plugins

### ISSUE THREAD

**Issue by syzop** [unrealircd/unrealircd-webpanel#37]
Provide a (better) platform for developers to contribute their own plugins to the unrealircd/webpanel community.

(this idea is split off from Valware's Idea thread)

Administrative considerations:
- Github repo? I think this will be the right method
- Plugin quality standards? (minimum requirements for contribution etc)

Interface (GUI):
- Plugins page to contain a list with wide overview cards similar to the Overview, which is also similar to how WordPress does it.
- Each plugin card to have an optional screenshot.
- When clicking to view a plugin from this list, in-depth detail about the plugin should be displayed, including description and author contact details.

**Comment by syzop** [comment]
I think this is a good idea and... i hope you are the one to do it ;)

**Comment by syzop** [comment]
https://github.com/unrealircd/unrealircd-webpanel-plugins exists now and you have full maintenance rights @ValwareIRC

**Comment by ValwareIRC** [comment]
This has been completed
