### ISSUE TITLE
Fix/tidy styling in spamfilter table

### ISSUE THREAD

**Issue by TehPeGaSuS** [unrealircd/unrealircd-webpanel#41]
**Describe the bug**
If the spamfilter **mask** is too big other columns get out of screen. 

**To Reproduce**
1. Go to **Spamfilter**
2. Add a **long** spamfilter mask
3. Watch the issue happening

**Screenshots**
![spamfilter_no_wrap](https://github.com/unrealircd/unrealircd-webpanel/assets/25697531/8042a26c-103c-4697-9963-828a1817ba36)

___NOTE:___ the long spamfilters were hidden for security reasons.

**Comment by ValwareIRC** [comment]
Fixed by 8e30012
