### ISSUE TITLE
Deprecated: Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by Madriix** [unrealircd/unrealircd-webpanel#51]
https://github.com/unrealircd/unrealircd-webpanel-plugins/pull/3#issuecomment-2249181244

The error is on php 8.2.21

**Comment by ValwareIRC** [comment]
Thank you for your bug report. Please could you tell me if anything was affected on your webpanel, e.g some plugin didn't show properly or something?

And just to confirm with you, because I know you like to edit stuff, is this the right line?:
```$config['third-party-plugins']['data'] = $this->data;```

**Comment by Madriix** [comment]
@ValwareIRC The line is correct, I haven't changed it. I just remember that the PHP version changed from 8.2.x to another .x version 
The last time I installed a plugin was about two months ago, and it worked fine. Could it be due to the addition of the new plugin to the list?

**Comment by ValwareIRC** [comment]
Haha, I didn't close it as completed, I just mentioned it... @Madriix please could you see if this fixed the problem? ;D

**Comment by Madriix** [comment]
No, it doesn't install plugins, and at the very top there is this note :

` Deprecated: Automatic conversion of false to array is deprecated in /home/site/domains/labs.site..com/public_html/unrealircd-webpanel/Classes/class-plugin-git.php on line 18`

Maybe I broke something while trying to remove a plugin I had installed manually. I went to the list of plugins and clicked "uninstall," but it didn't uninstall. So, I deleted it manually and then tried to install it again from the plugin list, but without success.

**Comment by Madriix** [comment]
Maybe it's because of this in config.php:

```php
array (
  0 => 'sql_db'
),
```

Perhaps I should have rather put this (with the comma):

```php
array (
  0 => 'sql_db',
),
```

Maybe your modification last night broke it this time, but I'm not sure.

Could the problem be with Unrealircd 6.1.7?

I also replaced rpc-class read-only; with rpc-class full; in the Unrealircd configuration.

I reinstalled a new version of the web panel by deleting the old one.
The plugin installation still doesn't work.

**Comment by Madriix** [comment]
@ValwareIRC The bug is in the [`plugins.list`](https://api.valware.uk/plugins.list) file, try removing the firts 2 `{}` or the last two, and then it works. It's like the list is limited.

**Comment by Madriix** [comment]
I found the bug that has been hindering me for weeks in installing the plugins. It is located at this line : https://github.com/unrealircd/unrealircd-webpanel/blob/8e442abad75a0b1eb59526c0f85ded371da08ed3/js/bs-modal.js#L82 The create_plugin_info_modal function is duplicated. I removed one of them, and now it works fine

**Comment by Madriix** [comment]
It was a false alarm; the problem has returned. It was probably the cache. I copied the list of plugins locally and then reset the URL to Valware. The problem reappeared.

**Comment by ValwareIRC** [comment]
The root of the problem seems to be because the SQL plugin didn't define a big enough value in one of the table columns for it to hold the plugin information. Before my last commit, it was `VARCHAR(255)`.
If you re-install the webpanel, everything should work normally.
Alternatively if you feel comfortable enough, you can run the following SQL query which is a "hot-fix":
```
ALTER TABLE YourSQLPrefix_settings CHANGE setting_value setting_value LONGTEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL DEFAULT NULL
```
Of course remember to change "YourSQLPrefix" to the actual prefix you used in your SQL table names.

**Comment by Madriix** [comment]
@ValwareIRC ah yes, it works better now

I chose the second option to type directly in execute on phpmyadmin:
`ALTER TABLE unreal_settings CHANGE setting_value setting_value LONGTEXT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin NULL DEFAULT NULL`
